name: Bug Report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: syncthis version
      description: Run `syncthis --version` to find out.
      placeholder: "0.11.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - macOS
        - Linux
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js version
      description: Run `node --version` to find out.
      placeholder: "v20.11.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe what you expected vs. what actually happened.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Run `syncthis init …`
        2. …
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: Paste relevant output from `syncthis logs` (if applicable).
      render: shell
